version: 2

checkout:
  post:
    - ./ci-support/checkout_merge_commit.sh

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
      mkdir -p workspace
      git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
      python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &create_conda_env
    name: create_conda_env
    environment:
       CHANNELS: "-c cdat/label/nightly -c conda-forge -c cdat"
       PKGS: "nbformat testsrunner"
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       conda config --set always_yes yes --set changeps1 no
       conda update -y -q conda
       conda config --set anaconda_upload no
       if [[ $PY_VER = "py2" ]]; then
          conda create -q -n $PY_VER $CHANNELS $PKGS python=2
       else
          conda create -q -n $PY_VER $CHANNELS $PKGS python=3 $COVERAGE_PKGS
       fi

  - &setup_cdat_info
    name: setup_cdat_info
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export CDAT_ANONYMOUS_LOG=False
       source activate $PY_VER
       python setup.py install


  - &run_tests
    name: run_tests
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       export CDAT_ANONYMOUS_LOG=False
       export CDAT_SETUP_PATH=${HOME}
       source activate $PY_VER
       python run_tests.py -H -v2 -n 2 $COVERAGE
       RESULT=$?
       echo "*** $PY_VER test result: "${RESULT} 
       exit $RESULT

  - &conda_upload
    name: conda_upload
    environment:
       CHANNELS: "-c cdat/label/nightly -c conda-forge -c cdat"
    command: |
       if [[ $CIRCLE_BRANCH != 'master' ]]; then
          exit 0
       fi
       export PATH=${HOME}/project/$WORKDIR/miniconda/bin:$PATH
       conda install conda-build anaconda-client
       conda config --set anaconda_upload no
       export CONDA_BLD_PATH=`pwd`/conda_build
       git clone git://github.com/cdat/conda-recipes
       cd conda-recipes
       if [[ -d vcs ]]; then
          rm -rf cdat_info
       fi
       ln -s ../recipe cdat_info
       export PKG_NAME=cdat_info
       export USER=cdat
       export VERSION=8.2
       export LABEL=nightly
       python ./prep_for_build.py -l $VERSION -b $CIRCLE_BRANCH
       if [[ $PY_VER = 'py2' ]]; then
          conda build $PKG_NAME $CHANNELS --python=2.7
       else
          conda build $PKG_NAME $CHANNELS --python=3.6
          conda build $PKG_NAME $CHANNELS --python=3.7
       fi
       anaconda -t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL $CONDA_BLD_PATH/noarch/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force

  - &run_coveralls
    name: run_coveralls
    command: |
       export PATH=$WORKDIR/miniconda/bin:$PATH
       source activate $PY_VER
       coveralls
       source deactivate

jobs:
  macos_cdat_info_py2:
    macos:
      xcode: "9.2.0"
    environment:
      WORKDIR: "workspace/test_macos_cdat_info_py2"
      OS: "osx-64"
      PY_VER: "py2"
    steps:
      - checkout
      - run: *setup_miniconda
      - run: *create_conda_env
      - run: *setup_cdat_info
      - run: *run_tests
      - store_artifacts:
          path: tests_html
          destination: tests_html
      - store_artifacts:
          path: tests_png
          destination: tests_png

  macos_cdat_info_py3:
    macos:
      xcode: "9.2.0"
    environment:
      WORKDIR: "workspace/test_macos_cdat_info_py3"
      OS: "osx-64"
      PY_VER: "py3"
    steps:
      - checkout
      - run: *setup_miniconda
      - run: *create_conda_env
      - run: *setup_cdat_info
      - run: *run_tests
      - store_artifacts:
          path: tests_html
          destination: tests_html
      - store_artifacts:
          path: tests_png
          destination: tests_png

  linux_cdat_info_py2:
    machine:
      image: circleci/classic:latest
    environment:
      WORKDIR: "workspace/test_linux_cdat_info_py2"
      OS: "linux-64"
      PY_VER: "py2"
    steps:
      - checkout
      - run: *setup_miniconda
      - run: *create_conda_env
      - run: *setup_cdat_info
      - run: *run_tests
      - store_artifacts:
          path: tests_html
          destination: tests_html
      - store_artifacts:
          path: tests_png
          destination: tests_png

  linux_cdat_info_py3:
    machine:
      image: circleci/classic:latest
    environment:
      WORKDIR: "workspace/test_linux_cdat_info_py3"
      OS: "linux-64"
      PY_VER: "py3"
      COVERAGE: "-c tests/coverage.json --coverage-from-egg"
      COVERAGE_PKGS: "coverage coveralls"
    steps:
      - checkout
      - run: *setup_miniconda
      - run: *create_conda_env
      - run: *setup_cdat_info
      - run: *run_tests
      - run: *run_coveralls
      - run: *conda_upload
      - store_artifacts:
          path: tests_html
          destination: tests_html
      - store_artifacts:
          path: tests_png
          destination: tests_png

workflows:
  version: 2
  cdat_info:
    jobs:
      - macos_cdat_info_py2
      - macos_cdat_info_py3
      - linux_cdat_info_py2
      - linux_cdat_info_py3
